// SPDX-License-Identifier: MIT
//
// Splat Cleanup: interactively filters a Gaussian Splat PLY to remove floaters and
// reduce splat count, one step at a time.
//
// Workflow: Load a .ply once (data stays resident in memory), then apply filter steps
// individually — each step reports what it dropped and refines a running keep-mask.
// Write the current result to a new .ply at any point, bake it with the standard asset
// creator (Tools > Gaussian Splats), and inspect it in the scene before continuing.
//
// The heavy SOR (KNN) step runs as chunked background jobs so the editor stays
// responsive and can be cancelled mid-run. Output rows are copied verbatim from the
// input, so surviving splats are bit-exact (SH included).

using System;
using System.Collections.Generic;
using System.Linq;
using GaussianSplatting.Editor;
using GaussianSplatting.Editor.Utils;
using Unity.Burst;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Jobs;
using Unity.Mathematics;
using UnityEditor;
using UnityEngine;
using System.IO;
using System.Text;
using Debug = UnityEngine.Debug;

namespace R2B.Editor.GaussianCleanup
{
    [Serializable]
    public struct SplatCleanupParams
    {
        public float opacityMin;      // linear opacity after sigmoid, 0..1
        public float scaleMax;        // world units, largest ellipsoid axis after exp
        public int sorK;              // neighbors for mean-distance statistic
        public float sorStdRatio;     // drop if meanDist > mean + ratio * std
        public int targetCount;       // keep top-N by importance
        public float volumeExponent;  // importance = opacity * volume^exponent

        public static SplatCleanupParams Default => new()
        {
            opacityMin = 0.1f,
            scaleMax = 1.0f,
            sorK = 16,
            sorStdRatio = 2.0f,
            targetCount = 400_000,
            volumeExponent = 1f / 3f,
        };
    }

    // ---- Shared native helpers and jobs -------------------------------------------------

    static class SplatCleanupCore
    {
        public const int kMaxSorK = 32;

        public struct FloatOffsets
        {
            public int x, y, z, opacity, scale0, scale1, scale2;
        }

        public static bool TryGetFloatOffsets(
            List<(string, PLYFileReader.ElementType)> attrs, out FloatOffsets off, out string missing)
        {
            var wanted = new Dictionary<string, int>
            {
                { "x", -1 }, { "y", -1 }, { "z", -1 }, { "opacity", -1 },
                { "scale_0", -1 }, { "scale_1", -1 }, { "scale_2", -1 },
            };
            int offset = 0;
            foreach (var (attrName, attrType) in attrs)
            {
                if (attrType == PLYFileReader.ElementType.Float && wanted.ContainsKey(attrName) && wanted[attrName] < 0)
                    wanted[attrName] = offset;
                offset += PLYFileReader.TypeToSize(attrType);
            }
            var missingNames = new List<string>();
            foreach (var kv in wanted)
                if (kv.Value < 0)
                    missingNames.Add(kv.Key);
            missing = string.Join(",", missingNames);
            off = new FloatOffsets
            {
                x = wanted["x"], y = wanted["y"], z = wanted["z"],
                opacity = wanted["opacity"],
                scale0 = wanted["scale_0"], scale1 = wanted["scale_1"], scale2 = wanted["scale_2"],
            };
            return missingNames.Count == 0;
        }

        public static void WritePly(
            string path, List<(string, PLYFileReader.ElementType)> attrs, int stride,
            NativeArray<byte> raw, NativeArray<byte> keep, int outCount)
        {
            string dir = Path.GetDirectoryName(Path.GetFullPath(path));
            if (!string.IsNullOrEmpty(dir))
                Directory.CreateDirectory(dir);

            using var fs = new FileStream(path, FileMode.Create, FileAccess.Write);
            var header = new StringBuilder();
            header.Append("ply\n");
            header.Append("format binary_little_endian 1.0\n");
            header.Append("comment generated by R2B Splat Cleanup\n");
            header.Append($"element vertex {outCount}\n");
            foreach (var (attrName, attrType) in attrs)
                header.Append($"property {TypeName(attrType)} {attrName}\n");
            header.Append("end_header\n");
            byte[] headerBytes = Encoding.ASCII.GetBytes(header.ToString());
            fs.Write(headerBytes, 0, headerBytes.Length);

            const int kRowsPerChunk = 65536;
            byte[] buffer = new byte[kRowsPerChunk * stride];
            int bufRows = 0;
            for (int i = 0; i < keep.Length; ++i)
            {
                if (keep[i] == 0)
                    continue;
                NativeArray<byte>.Copy(raw, i * stride, buffer, bufRows * stride, stride);
                if (++bufRows == kRowsPerChunk)
                {
                    fs.Write(buffer, 0, bufRows * stride);
                    bufRows = 0;
                }
            }
            if (bufRows > 0)
                fs.Write(buffer, 0, bufRows * stride);
        }

        static string TypeName(PLYFileReader.ElementType t) => t switch
        {
            PLYFileReader.ElementType.Float => "float",
            PLYFileReader.ElementType.Double => "double",
            PLYFileReader.ElementType.UChar => "uchar",
            _ => throw new ArgumentOutOfRangeException(nameof(t)),
        };

        [BurstCompile]
        public unsafe struct ExtractJob : IJobParallelFor
        {
            [NativeDisableUnsafePtrRestriction] public byte* raw;
            public long stride;
            public FloatOffsets off;
            [WriteOnly] public NativeArray<float3> pos;
            [WriteOnly] public NativeArray<float> opacity;
            [WriteOnly] public NativeArray<float> maxScale;
            [WriteOnly] public NativeArray<float> volume;
            [WriteOnly] public NativeArray<byte> finite;

            public void Execute(int i)
            {
                byte* v = raw + i * stride;
                float3 p = new float3(Read(v, off.x), Read(v, off.y), Read(v, off.z));
                float rawOp = Read(v, off.opacity);
                float3 rawS = new float3(Read(v, off.scale0), Read(v, off.scale1), Read(v, off.scale2));
                bool ok = math.all(math.isfinite(p)) && math.isfinite(rawOp) && math.all(math.isfinite(rawS));
                float3 s = math.exp(rawS);
                float op = math.rcp(1f + math.exp(-rawOp));
                pos[i] = p;
                opacity[i] = op;
                maxScale[i] = math.cmax(s);
                volume[i] = s.x * s.y * s.z;
                finite[i] = ok ? (byte)1 : (byte)0;
            }

            static float Read(byte* v, int offset) => *(float*)(v + offset);
        }

        [BurstCompile]
        public struct BuildGridJob : IJobParallelFor
        {
            [ReadOnly] public NativeArray<float3> pos;
            [ReadOnly] public NativeArray<byte> keep;
            public float3 origin;
            public float invCell;
            public NativeParallelMultiHashMap<int3, int>.ParallelWriter grid;

            public void Execute(int i)
            {
                if (keep[i] == 0)
                    return;
                int3 c = (int3)math.floor((pos[i] - origin) * invCell);
                grid.Add(c, i);
            }
        }

        // Computes the mean distance to the k nearest neighbours for points in
        // [rangeStart, rangeStart+count). Runs on a sub-range so it can be chunked and
        // cancelled between dispatches. keep==0 points are marked -1 and skipped later.
        [BurstCompile]
        public struct SorMeanDistJob : IJobParallelFor
        {
            [ReadOnly] public NativeArray<float3> pos;
            [ReadOnly] public NativeArray<byte> keep;
            [ReadOnly] public NativeParallelMultiHashMap<int3, int> grid;
            public float3 origin;
            public float invCell;
            public int k;
            public int rangeStart;
            [NativeDisableParallelForRestriction] public NativeArray<float> meanDist;

            public unsafe void Execute(int local)
            {
                int i = rangeStart + local;
                if (keep[i] == 0)
                {
                    meanDist[i] = -1f;
                    return;
                }
                float* best = stackalloc float[kMaxSorK];
                float3 p = pos[i];
                int3 c = (int3)math.floor((p - origin) * invCell);
                int found = Gather(p, c, 1, best, i);
                if (found < k)
                    found = Gather(p, c, 2, best, i);
                if (found == 0)
                {
                    meanDist[i] = float.MaxValue;
                    return;
                }
                float sum = 0;
                for (int j = 0; j < found; ++j)
                    sum += math.sqrt(best[j]);
                meanDist[i] = sum / found;
            }

            unsafe int Gather(float3 p, int3 c, int radius, float* best, int self)
            {
                int count = 0;
                for (int dz = -radius; dz <= radius; ++dz)
                for (int dy = -radius; dy <= radius; ++dy)
                for (int dx = -radius; dx <= radius; ++dx)
                {
                    int3 cell = c + new int3(dx, dy, dz);
                    if (!grid.TryGetFirstValue(cell, out int j, out var it))
                        continue;
                    do
                    {
                        if (j == self)
                            continue;
                        float d = math.distancesq(p, pos[j]);
                        if (count < k)
                        {
                            best[count++] = d;
                        }
                        else
                        {
                            int worstIdx = 0;
                            float worst = best[0];
                            for (int m = 1; m < k; ++m)
                            {
                                if (best[m] > worst)
                                {
                                    worst = best[m];
                                    worstIdx = m;
                                }
                            }
                            if (d < worst)
                                best[worstIdx] = d;
                        }
                    } while (grid.TryGetNextValue(out j, ref it));
                }
                return count;
            }
        }
    }

    // ---- Resident session that owns the loaded splat data -------------------------------

    sealed class CleanupSession : IDisposable
    {
        public string InputPath { get; private set; }
        public int InputCount { get; private set; }
        public int Stride { get; private set; }
        public int KeptCount { get; private set; }
        public bool IsLoaded => m_Raw.IsCreated;

        NativeArray<byte> m_Raw;
        NativeArray<float3> m_Pos;
        NativeArray<float> m_Opacity;
        NativeArray<float> m_MaxScale;
        NativeArray<float> m_Volume;
        NativeArray<byte> m_Finite;
        NativeArray<byte> m_Keep;
        List<(string, PLYFileReader.ElementType)> m_Attrs;

        readonly StringBuilder m_Log;

        // async SOR state
        public bool SorRunning { get; private set; }
        public string SorProgress { get; private set; }
        NativeParallelMultiHashMap<int3, int> m_SorGrid;
        NativeArray<float> m_SorMeanDist;
        JobHandle m_SorHandle;
        bool m_SorScheduled;
        bool m_SorCancel;
        int m_SorCursor;
        int m_SorK;
        float m_SorStdRatio;
        float3 m_SorOrigin;
        float m_SorInvCell;

        const int kSorChunk = 262144;

        public CleanupSession(StringBuilder log) => m_Log = log;

        public bool Load(string inputPath)
        {
            Dispose();
            try
            {
                PLYFileReader.ReadFile(inputPath, out int count, out int stride, out var attrs, out m_Raw);
                if (count <= 0)
                {
                    m_Log.AppendLine("Input PLY has no vertices.");
                    Dispose();
                    return false;
                }
                foreach (var (attrName, attrType) in attrs)
                {
                    if (attrType == PLYFileReader.ElementType.None)
                    {
                        m_Log.AppendLine($"Unsupported property type on '{attrName}' — only float/double/uchar PLY are supported.");
                        Dispose();
                        return false;
                    }
                }
                if (!SplatCleanupCore.TryGetFloatOffsets(attrs, out var off, out string missing))
                {
                    m_Log.AppendLine($"Not a Gaussian Splat PLY, missing float properties: {missing}");
                    Dispose();
                    return false;
                }

                InputPath = inputPath;
                InputCount = count;
                Stride = stride;
                m_Attrs = attrs;

                m_Pos = new NativeArray<float3>(count, Allocator.Persistent, NativeArrayOptions.UninitializedMemory);
                m_Opacity = new NativeArray<float>(count, Allocator.Persistent, NativeArrayOptions.UninitializedMemory);
                m_MaxScale = new NativeArray<float>(count, Allocator.Persistent, NativeArrayOptions.UninitializedMemory);
                m_Volume = new NativeArray<float>(count, Allocator.Persistent, NativeArrayOptions.UninitializedMemory);
                m_Finite = new NativeArray<byte>(count, Allocator.Persistent, NativeArrayOptions.UninitializedMemory);
                m_Keep = new NativeArray<byte>(count, Allocator.Persistent, NativeArrayOptions.UninitializedMemory);

                unsafe
                {
                    new SplatCleanupCore.ExtractJob
                    {
                        raw = (byte*)m_Raw.GetUnsafeReadOnlyPtr(),
                        stride = stride,
                        off = off,
                        pos = m_Pos,
                        opacity = m_Opacity,
                        maxScale = m_MaxScale,
                        volume = m_Volume,
                        finite = m_Finite,
                    }.Schedule(count, 65536).Complete();
                }

                for (int i = 0; i < count; ++i)
                    m_Keep[i] = 1;
                KeptCount = count;

                var fi = new FileInfo(inputPath);
                m_Log.AppendLine($"Loaded {count:N0} splats, {stride} B/splat, {EditorUtility.FormatBytes(fi.Length)} — {Path.GetFileName(inputPath)}");
                LogDistributions();
                return true;
            }
            catch (Exception ex)
            {
                m_Log.AppendLine($"ERROR loading: {ex.Message}");
                Debug.LogException(ex);
                Dispose();
                return false;
            }
        }

        void LogDistributions()
        {
            int n = InputCount, kept = 0, invalid = 0;
            int b001 = 0, b005 = 0, b01 = 0, b02 = 0, b03 = 0;
            for (int i = 0; i < n; ++i)
            {
                if (m_Keep[i] == 0)
                    continue;
                ++kept;
                if (m_Finite[i] == 0)
                    ++invalid;
                float op = m_Opacity[i];
                if (op < 0.01f) ++b001;
                if (op < 0.05f) ++b005;
                if (op < 0.1f) ++b01;
                if (op < 0.2f) ++b02;
                if (op < 0.3f) ++b03;
            }
            if (kept == 0)
                return;
            m_Log.AppendLine($"  NaN/Inf splats: {invalid:N0}");
            m_Log.AppendLine($"  Opacity <0.01/0.05/0.1/0.2/0.3: {Pct(b001, kept)} / {Pct(b005, kept)} / {Pct(b01, kept)} / {Pct(b02, kept)} / {Pct(b03, kept)}");

            var scales = new NativeArray<float>(kept, Allocator.TempJob, NativeArrayOptions.UninitializedMemory);
            int w = 0;
            for (int i = 0; i < n; ++i)
                if (m_Keep[i] != 0)
                    scales[w++] = m_MaxScale[i];
            scales.SortJob().Schedule().Complete();
            m_Log.AppendLine($"  Max scale p50 {Perc(scales, 0.5):0.####}, p90 {Perc(scales, 0.9):0.####}, " +
                             $"p99 {Perc(scales, 0.99):0.####}, p99.9 {Perc(scales, 0.999):0.####}, max {scales[kept - 1]:0.####}");
            scales.Dispose();
        }

        static string Pct(int part, int total) => $"{100.0 * part / total:0.##}%";

        static float Perc(NativeArray<float> sorted, double q) =>
            sorted[(int)math.clamp((long)(q * (sorted.Length - 1)), 0, sorted.Length - 1)];

        public void ApplyInvalid()
        {
            int dropped = 0;
            for (int i = 0; i < InputCount; ++i)
            {
                if (m_Keep[i] != 0 && m_Finite[i] == 0)
                {
                    m_Keep[i] = 0;
                    ++dropped;
                }
            }
            KeptCount -= dropped;
            m_Log.AppendLine($"[NaN/Inf] dropped {dropped:N0} → kept {KeptCount:N0}");
        }

        public void ApplyOpacity(float min)
        {
            int dropped = 0;
            for (int i = 0; i < InputCount; ++i)
            {
                if (m_Keep[i] != 0 && m_Opacity[i] < min)
                {
                    m_Keep[i] = 0;
                    ++dropped;
                }
            }
            KeptCount -= dropped;
            m_Log.AppendLine($"[Opacity <{min:0.###}] dropped {dropped:N0} → kept {KeptCount:N0}");
        }

        public void ApplyScale(float max)
        {
            int dropped = 0;
            for (int i = 0; i < InputCount; ++i)
            {
                if (m_Keep[i] != 0 && m_MaxScale[i] > max)
                {
                    m_Keep[i] = 0;
                    ++dropped;
                }
            }
            KeptCount -= dropped;
            m_Log.AppendLine($"[Scale >{max:0.###}] dropped {dropped:N0} → kept {KeptCount:N0}");
        }

        public void ApplyBudget(int target, float volumeExponent)
        {
            if (KeptCount <= target)
            {
                m_Log.AppendLine($"[Budget {target:N0}] kept {KeptCount:N0} already ≤ target, nothing dropped");
                return;
            }
            var order = new NativeArray<ImportanceIndex>(KeptCount, Allocator.TempJob, NativeArrayOptions.UninitializedMemory);
            int w = 0;
            for (int i = 0; i < InputCount; ++i)
            {
                if (m_Keep[i] == 0)
                    continue;
                float imp = m_Opacity[i] * math.pow(math.max(m_Volume[i], 0f), volumeExponent);
                order[w++] = new ImportanceIndex { importance = imp, index = i };
            }
            order.SortJob(new ImportanceDescComparer()).Schedule().Complete();
            for (int i = target; i < KeptCount; ++i)
                m_Keep[order[i].index] = 0;
            int dropped = KeptCount - target;
            order.Dispose();
            KeptCount = target;
            m_Log.AppendLine($"[Budget {target:N0}] (importance = opacity·volume^{volumeExponent:0.###}) dropped {dropped:N0} → kept {KeptCount:N0}");
        }

        struct ImportanceIndex
        {
            public float importance;
            public int index;
        }

        struct ImportanceDescComparer : IComparer<ImportanceIndex>
        {
            public int Compare(ImportanceIndex a, ImportanceIndex b) => b.importance.CompareTo(a.importance);
        }

        // ---- SOR (async, chunked, cancellable) ----

        public void SorBegin(int k, float stdRatio)
        {
            if (SorRunning)
                return;
            k = math.clamp(k, 2, SplatCleanupCore.kMaxSorK);
            if (KeptCount <= k + 1)
            {
                m_Log.AppendLine($"[SOR] only {KeptCount:N0} kept splats — need > {k + 1}, skipped");
                return;
            }

            GetRobustBounds(out float3 bmin, out float3 bmax);
            float3 ext = math.max(bmax - bmin, 1e-6f);
            float cellSize = math.pow(ext.x * ext.y * ext.z / KeptCount, 1f / 3f) * 2f;

            // Splats sit on surfaces, so a volume-based cell estimate can be far off.
            // Build once, measure per-point occupancy, resize until scans stay cheap.
            const float kTargetOcc = 3f;
            for (int iter = 0; ; ++iter)
            {
                if (m_SorGrid.IsCreated) m_SorGrid.Dispose();
                m_SorGrid = new NativeParallelMultiHashMap<int3, int>(KeptCount, Allocator.Persistent);
                new SplatCleanupCore.BuildGridJob
                {
                    pos = m_Pos, keep = m_Keep, origin = bmin, invCell = 1f / cellSize,
                    grid = m_SorGrid.AsParallelWriter(),
                }.Schedule(InputCount, 65536).Complete();

                float occ = SampleWeightedOccupancy(bmin, 1f / cellSize);
                if (iter >= 3 || (occ >= 0.75f && occ <= 8f))
                    break;
                cellSize *= math.pow(kTargetOcc / math.max(occ, 1e-3f), 1f / 2.5f);
            }

            m_SorMeanDist = new NativeArray<float>(InputCount, Allocator.Persistent, NativeArrayOptions.UninitializedMemory);
            m_SorOrigin = bmin;
            m_SorInvCell = 1f / cellSize;
            m_SorK = k;
            m_SorStdRatio = stdRatio;
            m_SorCursor = 0;
            m_SorScheduled = false;
            m_SorCancel = false;
            SorRunning = true;
            SorProgress = $"SOR 0 / {InputCount:N0}";
            m_Log.AppendLine($"[SOR] started (k={k}, std={stdRatio:0.##}) over {InputCount:N0} rows…");
        }

        public void SorCancel() => m_SorCancel = true;

        // Drives one poll of the async SOR. Returns true while still running.
        public bool SorTick()
        {
            if (!SorRunning)
                return false;
            try
            {
                if (m_SorScheduled)
                {
                    if (!m_SorHandle.IsCompleted)
                        return true;
                    m_SorHandle.Complete();
                    m_SorScheduled = false;
                    m_SorCursor = math.min(m_SorCursor + kSorChunk, InputCount);
                    SorProgress = $"SOR {m_SorCursor:N0} / {InputCount:N0}";

                    if (m_SorCancel)
                    {
                        m_Log.AppendLine("[SOR] cancelled — keep-mask unchanged");
                        SorCleanup();
                        return false;
                    }
                    if (m_SorCursor >= InputCount)
                    {
                        SorFinish();
                        return false;
                    }
                }

                int len = math.min(kSorChunk, InputCount - m_SorCursor);
                m_SorHandle = new SplatCleanupCore.SorMeanDistJob
                {
                    pos = m_Pos, keep = m_Keep, grid = m_SorGrid,
                    origin = m_SorOrigin, invCell = m_SorInvCell, k = m_SorK,
                    rangeStart = m_SorCursor, meanDist = m_SorMeanDist,
                }.Schedule(len, 4096);
                m_SorScheduled = true;
                JobHandle.ScheduleBatchedJobs();
                return true;
            }
            catch (Exception ex)
            {
                m_Log.AppendLine($"[SOR] ERROR: {ex.Message}");
                Debug.LogException(ex);
                SorCleanup();
                return false;
            }
        }

        void SorFinish()
        {
            double sum = 0, sumSq = 0;
            long valid = 0;
            for (int i = 0; i < InputCount; ++i)
            {
                if (m_Keep[i] == 0 || m_SorMeanDist[i] >= float.MaxValue || m_SorMeanDist[i] < 0f)
                    continue;
                float md = m_SorMeanDist[i];
                sum += md;
                sumSq += (double)md * md;
                ++valid;
            }
            int dropped = 0;
            if (valid > 1)
            {
                double mean = sum / valid;
                double std = math.sqrt(math.max(0, sumSq / valid - mean * mean));
                float threshold = (float)(mean + m_SorStdRatio * std);
                for (int i = 0; i < InputCount; ++i)
                {
                    if (m_Keep[i] != 0 && (m_SorMeanDist[i] > threshold || m_SorMeanDist[i] >= float.MaxValue))
                    {
                        m_Keep[i] = 0;
                        ++dropped;
                    }
                }
                KeptCount -= dropped;
                m_Log.AppendLine($"[SOR] k={m_SorK} std={m_SorStdRatio:0.##}: mean {mean:0.####} std {std:0.####} → threshold {threshold:0.####}, dropped {dropped:N0} → kept {KeptCount:N0}");
            }
            else
            {
                m_Log.AppendLine("[SOR] not enough neighbours found, nothing dropped");
            }
            SorCleanup();
        }

        void SorCleanup()
        {
            if (m_SorScheduled)
            {
                m_SorHandle.Complete();
                m_SorScheduled = false;
            }
            if (m_SorGrid.IsCreated) m_SorGrid.Dispose();
            if (m_SorMeanDist.IsCreated) m_SorMeanDist.Dispose();
            SorRunning = false;
            SorProgress = null;
        }

        void GetRobustBounds(out float3 bmin, out float3 bmax)
        {
            const int kSamples = 100_000;
            int step = math.max(1, KeptCount / kSamples);
            var xs = new List<float>(kSamples + 1);
            var ys = new List<float>(kSamples + 1);
            var zs = new List<float>(kSamples + 1);
            int seen = 0;
            for (int i = 0; i < InputCount; ++i)
            {
                if (m_Keep[i] == 0)
                    continue;
                if (seen++ % step != 0)
                    continue;
                float3 p = m_Pos[i];
                xs.Add(p.x); ys.Add(p.y); zs.Add(p.z);
            }
            xs.Sort(); ys.Sort(); zs.Sort();
            int lo = (int)(xs.Count * 0.001), hi = math.max(lo, (int)(xs.Count * 0.999) - 1);
            bmin = new float3(xs[lo], ys[lo], zs[lo]);
            bmax = new float3(xs[hi], ys[hi], zs[hi]);
            float3 margin = math.max(bmax - bmin, 1e-3f) * 0.1f;
            bmin -= margin;
            bmax += margin;
        }

        float SampleWeightedOccupancy(float3 origin, float invCell)
        {
            const int kSamples = 50_000;
            long sum = 0;
            int taken = 0, seen = 0;
            int step = math.max(1, InputCount / kSamples);
            for (int i = 0; i < InputCount && taken < kSamples; ++i)
            {
                if (m_Keep[i] == 0)
                    continue;
                if (seen++ % step != 0)
                    continue;
                int3 c = (int3)math.floor((m_Pos[i] - origin) * invCell);
                sum += m_SorGrid.CountValuesForKey(c);
                ++taken;
            }
            return taken > 0 ? (float)sum / taken : 0f;
        }

        public void ResetKeep()
        {
            if (!IsLoaded)
                return;
            for (int i = 0; i < InputCount; ++i)
                m_Keep[i] = 1;
            KeptCount = InputCount;
            m_Log.AppendLine($"[Reset] keep-mask restored → kept {KeptCount:N0}");
        }

        public bool WritePly(string outputPath)
        {
            if (!IsLoaded)
                return false;
            if (KeptCount == 0)
            {
                m_Log.AppendLine("Nothing kept — refusing to write an empty PLY.");
                return false;
            }
            try
            {
                SplatCleanupCore.WritePly(outputPath, m_Attrs, Stride, m_Raw, m_Keep, KeptCount);
                var fi = new FileInfo(outputPath);
                m_Log.AppendLine($"Wrote {KeptCount:N0} splats → {outputPath} ({EditorUtility.FormatBytes(fi.Length)})");
                return true;
            }
            catch (Exception ex)
            {
                m_Log.AppendLine($"ERROR writing: {ex.Message}");
                Debug.LogException(ex);
                return false;
            }
        }

        public void Dispose()
        {
            SorCleanup();
            if (m_Raw.IsCreated) m_Raw.Dispose();
            if (m_Pos.IsCreated) m_Pos.Dispose();
            if (m_Opacity.IsCreated) m_Opacity.Dispose();
            if (m_MaxScale.IsCreated) m_MaxScale.Dispose();
            if (m_Volume.IsCreated) m_Volume.Dispose();
            if (m_Finite.IsCreated) m_Finite.Dispose();
            if (m_Keep.IsCreated) m_Keep.Dispose();
            InputCount = 0;
            KeptCount = 0;
        }
    }

    // ---- Editor window ------------------------------------------------------------------

    public class SplatCleanupWindow : EditorWindow
    {
        const string kPref = "com.r2b.SplatCleanup.";

        readonly FilePickerControl m_InputPicker = new();
        readonly FilePickerControl m_OutputPicker = new();
        readonly StringBuilder m_Log = new();

        [SerializeField] string m_InputPath;
        [SerializeField] string m_OutputPath;
        [SerializeField] SplatCleanupParams m_Params = SplatCleanupParams.Default;
        [SerializeField] Vector2 m_LogScroll;

        CleanupSession m_Session;

        [MenuItem("R2B/Gaussian Splats/Splat Cleanup (PLY)")]
        public static void Init()
        {
            var window = GetWindow<SplatCleanupWindow>(false, "Splat Cleanup", true);
            window.minSize = new Vector2(440, 640);
            window.Show();
        }

        void OnEnable()
        {
            m_InputPath = EditorPrefs.GetString(kPref + "Input", m_InputPath);
            m_OutputPath = EditorPrefs.GetString(kPref + "Output", m_OutputPath);
            string json = EditorPrefs.GetString(kPref + "Params", null);
            if (!string.IsNullOrEmpty(json))
            {
                try { m_Params = JsonUtility.FromJson<SplatCleanupParams>(json); }
                catch { m_Params = SplatCleanupParams.Default; }
            }
            EditorApplication.update += OnEditorUpdate;
            AssemblyReloadEvents.beforeAssemblyReload += FreeSession;
        }

        void OnDisable()
        {
            EditorApplication.update -= OnEditorUpdate;
            AssemblyReloadEvents.beforeAssemblyReload -= FreeSession;
            EditorPrefs.SetString(kPref + "Input", m_InputPath ?? "");
            EditorPrefs.SetString(kPref + "Output", m_OutputPath ?? "");
            EditorPrefs.SetString(kPref + "Params", JsonUtility.ToJson(m_Params));
            FreeSession();
        }

        void OnDestroy() => FreeSession();

        void FreeSession()
        {
            m_Session?.Dispose();
            m_Session = null;
        }

        void OnEditorUpdate()
        {
            if (m_Session != null && m_Session.SorRunning)
            {
                m_Session.SorTick();
                Repaint();
            }
        }

        bool Loaded => m_Session != null && m_Session.IsLoaded;
        bool Busy => m_Session != null && m_Session.SorRunning;

        void OnGUI()
        {
            DrawFiles();
            DrawSession();
            DrawSteps();
            DrawOutput();
            DrawLog();
        }

        void DrawFiles()
        {
            EditorGUILayout.Space(6);
            EditorGUILayout.LabelField("1. Files", EditorStyles.boldLabel);
            using (new EditorGUI.DisabledScope(Busy))
            {
                var rect = EditorGUILayout.GetControlRect();
                m_InputPath = m_InputPicker.PathFieldGUI(rect, new GUIContent("Input PLY"), m_InputPath, "ply", "SplatCleanupInput");
                rect = EditorGUILayout.GetControlRect();
                m_OutputPath = m_OutputPicker.PathFieldGUI(rect, new GUIContent("Output PLY"), m_OutputPath, "ply", "SplatCleanupOutput", saveDialog: true);
                using (new EditorGUILayout.HorizontalScope())
                {
                    if (!string.IsNullOrWhiteSpace(m_OutputPath))
                    {
                        if (GUILayout.Button("Clear output", GUILayout.Width(100)))
                            m_OutputPath = null;
                    }
                    else if (!string.IsNullOrWhiteSpace(m_InputPath))
                    {
                        if (GUILayout.Button("Use <input>_clean.ply", GUILayout.Width(180)))
                            m_OutputPath = DefaultOutputPath(m_InputPath);
                    }
                    GUILayout.FlexibleSpace();
                }
            }
        }

        void DrawSession()
        {
            EditorGUILayout.Space(6);
            EditorGUILayout.LabelField("2. Session", EditorStyles.boldLabel);
            bool hasInput = !string.IsNullOrWhiteSpace(m_InputPath) && File.Exists(m_InputPath);
            using (new EditorGUILayout.HorizontalScope())
            {
                using (new EditorGUI.DisabledScope(!hasInput || Busy))
                {
                    if (GUILayout.Button(Loaded ? "Reload PLY" : "Load PLY", GUILayout.Height(22)))
                        DoLoad();
                }
                using (new EditorGUI.DisabledScope(!Loaded || Busy))
                {
                    if (GUILayout.Button("Free", GUILayout.Width(70), GUILayout.Height(22)))
                    {
                        FreeSession();
                        m_Log.AppendLine("Session freed.");
                    }
                }
            }
            if (Loaded)
                EditorGUILayout.HelpBox(
                    $"Input {m_Session.InputCount:N0} splats · currently kept {m_Session.KeptCount:N0} " +
                    $"({100.0 * m_Session.KeptCount / math.max(1, m_Session.InputCount):0.#}%)",
                    MessageType.Info);
            else
                EditorGUILayout.HelpBox("Load a PLY to begin. Data stays resident so you can apply steps one at a time.", MessageType.None);
        }

        void DrawSteps()
        {
            EditorGUILayout.Space(6);
            EditorGUILayout.LabelField("3. Steps — apply one at a time, then inspect in scene", EditorStyles.boldLabel);

            using (new EditorGUI.DisabledScope(!Loaded || Busy))
            {
                if (GUILayout.Button("Step: Remove NaN/Inf"))
                    Step(m_Session.ApplyInvalid);

                using (new EditorGUILayout.HorizontalScope())
                {
                    m_Params.opacityMin = EditorGUILayout.Slider("Min opacity", m_Params.opacityMin, 0f, 1f);
                    if (GUILayout.Button("Apply", GUILayout.Width(70)))
                        Step(() => m_Session.ApplyOpacity(m_Params.opacityMin));
                }

                using (new EditorGUILayout.HorizontalScope())
                {
                    m_Params.scaleMax = EditorGUILayout.FloatField(
                        new GUIContent("Max scale (world)", "Largest ellipsoid axis; see the p50/p90/p99 printout after Load"),
                        m_Params.scaleMax);
                    if (GUILayout.Button("Apply", GUILayout.Width(70)))
                        Step(() => m_Session.ApplyScale(m_Params.scaleMax));
                }
            }

            // SOR row: either Apply (idle) or progress + Cancel (running)
            using (new EditorGUILayout.HorizontalScope())
            {
                m_Params.sorK = EditorGUILayout.IntSlider(new GUIContent("SOR neighbors (k)"), m_Params.sorK, 2, 32);
            }
            using (new EditorGUILayout.HorizontalScope())
            {
                m_Params.sorStdRatio = EditorGUILayout.Slider(
                    new GUIContent("SOR std ratio", "Lower removes more; drop if mean k-NN dist > mean + ratio·std"),
                    m_Params.sorStdRatio, 0.5f, 4f);
            }
            if (Busy)
            {
                using (new EditorGUILayout.HorizontalScope())
                {
                    EditorGUILayout.LabelField(m_Session.SorProgress ?? "SOR running…");
                    if (GUILayout.Button("Cancel", GUILayout.Width(80)))
                        m_Session.SorCancel();
                }
                var r = EditorGUILayout.GetControlRect(false, 4);
                float frac = ParseProgressFraction(m_Session.SorProgress);
                EditorGUI.ProgressBar(r, frac, "");
            }
            else
            {
                using (new EditorGUI.DisabledScope(!Loaded))
                {
                    if (GUILayout.Button("Step: Statistical Outlier Removal (background)"))
                    {
                        m_Session.SorBegin(m_Params.sorK, m_Params.sorStdRatio);
                        ScrollToBottom();
                    }
                }
            }

            using (new EditorGUI.DisabledScope(!Loaded || Busy))
            {
                using (new EditorGUILayout.HorizontalScope())
                {
                    m_Params.targetCount = math.max(1, EditorGUILayout.IntField("Target count", m_Params.targetCount));
                    m_Params.volumeExponent = EditorGUILayout.Slider(
                        new GUIContent("vol^exp", "importance = opacity · volume^exp"),
                        m_Params.volumeExponent, 0f, 1f);
                }
                if (GUILayout.Button("Step: Budget to target (importance ranked)"))
                    Step(() => m_Session.ApplyBudget(m_Params.targetCount, m_Params.volumeExponent));

                EditorGUILayout.Space(2);
                if (GUILayout.Button("Reset keep-mask (undo all steps)"))
                    Step(m_Session.ResetKeep);
            }
        }

        void DrawOutput()
        {
            EditorGUILayout.Space(6);
            EditorGUILayout.LabelField("4. Output", EditorStyles.boldLabel);
            bool canWrite = Loaded && !Busy && !string.IsNullOrWhiteSpace(m_OutputPath) &&
                            !PathsEqual(m_InputPath, m_OutputPath);
            using (new EditorGUI.DisabledScope(!canWrite))
            {
                if (GUILayout.Button("Write current keep-mask → PLY", GUILayout.Height(24)))
                {
                    string output = string.IsNullOrWhiteSpace(m_OutputPath) ? DefaultOutputPath(m_InputPath) : m_OutputPath;
                    m_Session.WritePly(output);
                    ScrollToBottom();
                }
            }
            if (Loaded && !string.IsNullOrWhiteSpace(m_OutputPath) && PathsEqual(m_InputPath, m_OutputPath))
                EditorGUILayout.HelpBox("Output path must differ from input.", MessageType.Warning);
            if (GUILayout.Button("Open GaussianSplatAsset Creator (bake new asset)"))
                GaussianSplatAssetCreator.Init();
        }

        void DrawLog()
        {
            EditorGUILayout.Space(4);
            using (new EditorGUILayout.HorizontalScope())
            {
                EditorGUILayout.LabelField("Log", EditorStyles.boldLabel);
                if (GUILayout.Button("Clear", GUILayout.Width(60)))
                    m_Log.Clear();
            }
            using (var scroll = new EditorGUILayout.ScrollViewScope(m_LogScroll, GUILayout.ExpandHeight(true)))
            {
                m_LogScroll = scroll.scrollPosition;
                EditorGUILayout.TextArea(m_Log.ToString(), GUILayout.ExpandHeight(true));
            }
        }

        void DoLoad()
        {
            m_Session ??= new CleanupSession(m_Log);
            m_Log.AppendLine($"—— Load {DateTime.Now:HH:mm:ss} ——");
            m_Session.Load(m_InputPath);
            m_Log.AppendLine();
            ScrollToBottom();
        }

        void Step(Action action)
        {
            if (!Loaded || Busy)
                return;
            action();
            ScrollToBottom();
        }

        void ScrollToBottom()
        {
            m_LogScroll.y = float.MaxValue;
            Repaint();
        }

        static float ParseProgressFraction(string progress)
        {
            if (string.IsNullOrEmpty(progress))
                return 0f;
            int slash = progress.IndexOf('/');
            if (slash < 0)
                return 0f;
            string a = new string(progress[..slash].Trim().Where(c => char.IsDigit(c)).ToArray());
            string b = new string(progress[(slash + 1)..].Trim().Where(c => char.IsDigit(c)).ToArray());
            if (long.TryParse(a, out long done) && long.TryParse(b, out long total) && total > 0)
                return math.clamp((float)done / total, 0f, 1f);
            return 0f;
        }

        static string DefaultOutputPath(string inputPath)
        {
            string dir = Path.GetDirectoryName(inputPath) ?? "";
            string name = Path.GetFileNameWithoutExtension(inputPath);
            return Path.Combine(dir, name + "_clean.ply").Replace('\\', '/');
        }

        static bool PathsEqual(string a, string b)
        {
            try { return string.Equals(Path.GetFullPath(a), Path.GetFullPath(b), StringComparison.OrdinalIgnoreCase); }
            catch { return false; }
        }
    }
}
